# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-30 15:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2018, 1, 30, 15, 7, 39, 226513, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
