# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-02 07:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180131_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('Event', 'Event'), ('Sports', 'Sports'), ('Fees', 'Fees'), ('Academic', 'Academic'), ('Result', 'Result'), ('Vyom', 'Vyom'), ('Function', 'Function')], default='Event', max_length=100)),
                ('slug', models.SlugField(default='event', help_text='This field will be automatically generated on Save')),
            ],
            options={
                'ordering': ('topic',),
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='category',
            name='post',
            field=models.ManyToManyField(to='posts.Post'),
        ),
    ]
