# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-02 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180202_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('topic',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='posts.Category'),
        ),
    ]
