# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-02 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20180202_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='topic',
            field=models.CharField(blank=True, choices=[('Event', 'Event'), ('Sports', 'Sports'), ('Fees', 'Fees'), ('Academic', 'Academic'), ('Result', 'Result'), ('Vyom', 'Vyom'), ('Function', 'Function')], default='Event', max_length=100),
        ),
    ]
