# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-14 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20180215_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('Mech', 'Mech'), ('Civil', 'Civil')], default='CSE', max_length=10),
            preserve_default=False,
        ),
    ]
